version: '3'

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "3001:3000"
    environment:
      - CONFIG_FILE_NAME=default.conf
      - TOKEN=abc
      - PROXY_URL=proxy.normans.co.za
      - PROXY_DOCKER_CONTAINER_NAME=nginx_custom_nginx_1
      - PROXY_DOCKER_CONTAINER_PORT=3000
    volumes:
      - ".:/app"
      - "./proxy/conf.d:/etc/nginx/conf.d"
      - "./proxy/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
