version: '3'

services:
  coxswain:
    build: .
    ports:
      - "81:80"
      - "443:443"
      - "3001:3000"
    command: 'sh entrypoint.sh'
    environment:
      - CONFIG_FILE_NAME=default.conf
      - TOKEN=abc
      - PROXY_URL=localhost
      - PROXY_DOCKER_CONTAINER_NAME=''
      - PROXY_DOCKER_CONTAINER_PORT=80
    # volumes:
      # - "./proxy/conf.d:/etc/nginx/conf.d"
      # - "./proxy/certs:/etc/nginx/certs"
      # - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
